package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuShaderModuleDescriptor extends WgpuJavaStruct {

    private final WgpuU32Array code = inner(WgpuU32Array.createHeap());

    private WgpuShaderModuleDescriptor(){}

    @Deprecated
    public WgpuShaderModuleDescriptor(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuShaderModuleDescriptor createHeap(){
        return new WgpuShaderModuleDescriptor();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuShaderModuleDescriptor createDirect(){
        var struct = new WgpuShaderModuleDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WgpuU32Array getCode(){
        return code;
    }

}