package com.noahcharlton.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuSwapChainStatus {
    GOOD,
    SUBOPTIMAL,
    TIMEOUT,
    OUTDATED,
    LOST,
    OUT_OF_MEMORY,
}