package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuBufferBinding extends WgpuJavaStruct {

    private final Struct.Unsigned64 buffer = new Struct.Unsigned64();
    private final Struct.Unsigned64 offset = new Struct.Unsigned64();
    private final Struct.Unsigned64 size = new Struct.Unsigned64();

    private WgpuBufferBinding(){}

    @Deprecated
    public WgpuBufferBinding(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuBufferBinding createHeap(){
        return new WgpuBufferBinding();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuBufferBinding createDirect(){
        var struct = new WgpuBufferBinding();
        struct.useDirectMemory();
        return struct;
    }


    public long getBuffer(){
        return buffer.get();
    }

    public void setBuffer(long x){
        this.buffer.set(x);
    }

    public long getOffset(){
        return offset.get();
    }

    public void setOffset(long x){
        this.offset.set(x);
    }

    public long getSize(){
        return size.get();
    }

    public void setSize(long x){
        this.size.set(x);
    }

}