package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuColor extends WgpuJavaStruct {

    private final Struct.Double r = new Struct.Double();
    private final Struct.Double g = new Struct.Double();
    private final Struct.Double b = new Struct.Double();
    private final Struct.Double a = new Struct.Double();

    private WgpuColor(){}

    @Deprecated
    public WgpuColor(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuColor createHeap(){
        return new WgpuColor();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuColor createDirect(){
        var struct = new WgpuColor();
        struct.useDirectMemory();
        return struct;
    }


    public double getR(){
        return r.get();
    }

    public void setR(double x){
        this.r.set(x);
    }

    public double getG(){
        return g.get();
    }

    public void setG(double x){
        this.g.set(x);
    }

    public double getB(){
        return b.get();
    }

    public void setB(double x){
        this.b.set(x);
    }

    public double getA(){
        return a.get();
    }

    public void setA(double x){
        this.a.set(x);
    }

}