package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuU32Array extends WgpuJavaStruct {

    private final Struct.Pointer bytes = new Struct.Pointer();
    private final Struct.Unsigned64 length = new Struct.Unsigned64();

    private WgpuU32Array(){}

    @Deprecated
    public WgpuU32Array(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuU32Array createHeap(){
        return new WgpuU32Array();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuU32Array createDirect(){
        var struct = new WgpuU32Array();
        struct.useDirectMemory();
        return struct;
    }


    public jnr.ffi.Pointer getBytes(){
        return bytes.get();
    }

    public void setBytes(jnr.ffi.Pointer x){
        this.bytes.set(x);
    }

    public long getLength(){
        return length.get();
    }

    public void setLength(long x){
        this.length.set(x);
    }

}