package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuCommandBufferDescriptor extends WgpuJavaStruct {

    private final Struct.Unsigned32 todo = new Struct.Unsigned32();

    private WgpuCommandBufferDescriptor(){}

    @Deprecated
    public WgpuCommandBufferDescriptor(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuCommandBufferDescriptor createHeap(){
        return new WgpuCommandBufferDescriptor();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuCommandBufferDescriptor createDirect(){
        var struct = new WgpuCommandBufferDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public long getTodo(){
        return todo.get();
    }

    public void setTodo(long x){
        this.todo.set(x);
    }

}