package com.noahcharlton.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuPresentMode {
     /**
       * The presentation engine does **not** wait for a vertical blanking period and
       * the request is presented immediately. This is a low-latency presentation mode,
       * but visible tearing may be observed. Will fallback to `Fifo` if unavailable on the
       * selected  platform and backend. Not optimal for mobile.
       */
    IMMEDIATE,
     /**
       * The presentation engine waits for the next vertical blanking period to update
       * the current image, but frames may be submitted without delay. This is a low-latency
       * presentation mode and visible tearing will **not** be observed. Will fallback to `Fifo`
       * if unavailable on the selected platform and backend. Not optimal for mobile.
       */
    MAILBOX,
     /**
       * The presentation engine waits for the next vertical blanking period to update
       * the current image. The framerate will be capped at the display refresh rate,
       * corresponding to the `VSync`. Tearing cannot be observed. Optimal for mobile.
       */
    FIFO,
}