package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuDepthStencilStateDescriptor extends WgpuJavaStruct {

    private final Struct.Enum<WgpuTextureFormat> format = new Struct.Enum<>(WgpuTextureFormat.class);
    private final Struct.Boolean depthWriteEnabled = new Struct.Boolean();
    private final Struct.Enum<WgpuCompareFunction> depthCompare = new Struct.Enum<>(WgpuCompareFunction.class);
    private final WgpuStencilStateFaceDescriptor stencilFront = inner(WgpuStencilStateFaceDescriptor.createHeap());
    private final WgpuStencilStateFaceDescriptor stencilBack = inner(WgpuStencilStateFaceDescriptor.createHeap());
    private final Struct.Unsigned32 stencilReadMask = new Struct.Unsigned32();
    private final Struct.Unsigned32 stencilWriteMask = new Struct.Unsigned32();

    private WgpuDepthStencilStateDescriptor(){}

    @Deprecated
    public WgpuDepthStencilStateDescriptor(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuDepthStencilStateDescriptor createHeap(){
        return new WgpuDepthStencilStateDescriptor();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuDepthStencilStateDescriptor createDirect(){
        var struct = new WgpuDepthStencilStateDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public WgpuTextureFormat getFormat(){
        return format.get();
    }

    public void setFormat(WgpuTextureFormat x){
        this.format.set(x);
    }

    public boolean getDepthWriteEnabled(){
        return depthWriteEnabled.get();
    }

    public void setDepthWriteEnabled(boolean x){
        this.depthWriteEnabled.set(x);
    }

    public WgpuCompareFunction getDepthCompare(){
        return depthCompare.get();
    }

    public void setDepthCompare(WgpuCompareFunction x){
        this.depthCompare.set(x);
    }

    public WgpuStencilStateFaceDescriptor getStencilFront(){
        return stencilFront;
    }

    public WgpuStencilStateFaceDescriptor getStencilBack(){
        return stencilBack;
    }

    public long getStencilReadMask(){
        return stencilReadMask.get();
    }

    public void setStencilReadMask(long x){
        this.stencilReadMask.set(x);
    }

    public long getStencilWriteMask(){
        return stencilWriteMask.get();
    }

    public void setStencilWriteMask(long x){
        this.stencilWriteMask.set(x);
    }

}