package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import com.noahcharlton.wgpuj.util.CStrPointer;
import com.noahcharlton.wgpuj.util.RustCString;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuBufferDescriptor extends WgpuJavaStruct {

    private final @CStrPointer Struct.Pointer label = new Struct.Pointer();
    private final Struct.Unsigned64 size = new Struct.Unsigned64();
    private final Struct.Unsigned32 usage = new Struct.Unsigned32();
    private final Struct.Boolean mappedAtCreation = new Struct.Boolean();

    private WgpuBufferDescriptor(){}

    @Deprecated
    public WgpuBufferDescriptor(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuBufferDescriptor createHeap(){
        return new WgpuBufferDescriptor();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuBufferDescriptor createDirect(){
        var struct = new WgpuBufferDescriptor();
        struct.useDirectMemory();
        return struct;
    }


    public java.lang.String getLabel(){
        return RustCString.fromPointer(label.get());
    }

    public void setLabel(java.lang.String x){
        this.label.set(RustCString.toPointer(x));
    }

    public long getSize(){
        return size.get();
    }

    public void setSize(long x){
        this.size.set(x);
    }

    public long getUsage(){
        return usage.get();
    }

    public void setUsage(long x){
        this.usage.set(x);
    }

    public boolean getMappedAtCreation(){
        return mappedAtCreation.get();
    }

    public void setMappedAtCreation(boolean x){
        this.mappedAtCreation.set(x);
    }

}