package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuTextureDataLayout extends WgpuJavaStruct {

    private final Struct.Unsigned64 offset = new Struct.Unsigned64();
    private final Struct.Unsigned32 bytesPerRow = new Struct.Unsigned32();
    private final Struct.Unsigned32 rowsPerImage = new Struct.Unsigned32();

    private WgpuTextureDataLayout(){}

    @Deprecated
    public WgpuTextureDataLayout(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuTextureDataLayout createHeap(){
        return new WgpuTextureDataLayout();
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuTextureDataLayout createDirect(){
        var struct = new WgpuTextureDataLayout();
        struct.useDirectMemory();
        return struct;
    }


    public long getOffset(){
        return offset.get();
    }

    public void setOffset(long x){
        this.offset.set(x);
    }

    public long getBytesPerRow(){
        return bytesPerRow.get();
    }

    public void setBytesPerRow(long x){
        this.bytesPerRow.set(x);
    }

    public long getRowsPerImage(){
        return rowsPerImage.get();
    }

    public void setRowsPerImage(long x){
        this.rowsPerImage.set(x);
    }

}