package com.noahcharlton.wgpuj.jni;

import com.noahcharlton.wgpuj.util.WgpuJavaStruct;
import jnr.ffi.Runtime;
import jnr.ffi.Struct;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public class WgpuBufferCopyView extends WgpuJavaStruct {

    private final Struct.Unsigned64 buffer = new Struct.Unsigned64();
    private final WgpuTextureDataLayout layout = inner(WgpuTextureDataLayout.createHeap());

    protected WgpuBufferCopyView(boolean direct){
         if(direct){
             useDirectMemory();
        }
    }

    @Deprecated
    public WgpuBufferCopyView(Runtime runtime){
        super(runtime);
    }

    /**
    * Creates this struct on the java heap.
    * In general, this should <b>not</b> be used because these structs
    * cannot be directly passed into native code. 
    */
    public static WgpuBufferCopyView createHeap(){
        return new WgpuBufferCopyView(false);
    }

    /**
    * Creates this struct in direct memory.
    * This is how most structs should be created (unless, they
    * are members of a nothing struct)
    * 
    * @see WgpuJavaStruct#useDirectMemory
    */
    public static WgpuBufferCopyView createDirect(){
        return new WgpuBufferCopyView(true);
    }


    public long getBuffer(){
        return buffer.get();
    }

    public void setBuffer(long x){
        this.buffer.set(x);
    }

    public WgpuTextureDataLayout getLayout(){
        return layout;
    }

}