package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuCDeviceType {
    /** Other. */
    OTHER,
    /** Integrated GPU with shared CPU/GPU memory. */
    INTEGRATED_GPU,
    /** Discrete GPU with separate CPU/GPU memory. */
    DISCRETE_GPU,
    /** Virtual / Hosted. */
    VIRTUAL_GPU,
    /** Cpu / Software Rendering. */
    CPU,
}
