package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuPolygonMode {
    /** Polygons are filled */
    FILL,
    /** Polygons are draw as line segments */
    LINE,
    /** Polygons are draw as points */
    POINT,
}
