package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public final class Wgpu{

    public static final int MAX_BIND_GROUPS = 8;
    public static final int MAX_COLOR_TARGETS = 4;
    public static final int MAX_MIP_LEVELS = 16;
    public static final int MAX_VERTEX_BUFFERS = 16;
    public static final int MAX_ANISOTROPY = 16;
    public static final int SHADER_STAGE_COUNT = 3;
    public static final int DESIRED_NUM_FRAMES = 3;
    /**
     * Buffer-Texture copies must have [`bytes_per_row`] aligned to this number.
     *
     * This doesn't apply to [`Queue::write_texture`].
     *
     * [`bytes_per_row`]: TextureDataLayout::bytes_per_row
     */
    public static final int COPY_BYTES_PER_ROW_ALIGNMENT = 256;
    /**
     * Alignment all push constants need
     */
    public static final int PUSH_CONSTANT_ALIGNMENT = 4;
    /**
     * Bound uniform/storage buffer offsets must be aligned to this number.
     */
    public static final int BIND_BUFFER_ALIGNMENT = 256;
    /**
     * Buffer to buffer copy offsets and sizes must be aligned to this number.
     */
    public static final int COPY_BUFFER_ALIGNMENT = 4;
    /**
     * Vertex buffer strides have to be aligned to this number.
     */
    public static final int VERTEX_STRIDE_ALIGNMENT = 4;

}