package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuCompareFunction {
     /**
       * Invalid value, do not use
       */
    UNDEFINED,
     /**
       * Function never passes
       */
    NEVER,
     /**
       * Function passes if new value less than existing value
       */
    LESS,
     /**
       * Function passes if new value is equal to existing value
       */
    EQUAL,
     /**
       * Function passes if new value is less than or equal to existing value
       */
    LESS_EQUAL,
     /**
       * Function passes if new value is greater than existing value
       */
    GREATER,
     /**
       * Function passes if new value is not equal to existing value
       */
    NOT_EQUAL,
     /**
       * Function passes if new value is greater than or equal to existing value
       */
    GREATER_EQUAL,
     /**
       * Function always passes
       */
    ALWAYS,
}