package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuFilterMode {
     /**
       * Nearest neighbor sampling.
       *
       * This creates a pixelated effect when used as a mag filter
       */
    NEAREST,
     /**
       * Linear Interpolation
       *
       * This makes textures smooth but blurry when used as a mag filter.
       */
    LINEAR,
}