package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuFrontFace {
    /**
     * Triangles with vertices in counter clockwise order are considered the front face.
     *
     * <p>This is the default with right handed coordinate spaces.
     */
    CCW,
    /**
     * Triangles with vertices in clockwise order are considered the front face.
     *
     * <p>This is the default with left handed coordinate spaces.
     */
    CW,
}
