package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuInputStepMode {
    /** Input data is advanced every vertex. This is the standard value for vertex data. */
    VERTEX,
    /** Input data is advanced every instance. */
    INSTANCE,
}
