package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuTextureDimension {
    /** 1D texture */
    D1,
    /** 2D texture */
    D2,
    /** 3D texture */
    D3,
}
