package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuCullMode {
    /** No faces should be culled */
    NONE,
    /** Front faces should be culled */
    FRONT,
    /** Back faces should be culled */
    BACK,
}
