package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuIndexFormat {
    /** Indices are 16 bit unsigned integers. */
    UINT16,
    /** Indices are 32 bit unsigned integers. */
    UINT32,
}
