package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuPowerPreference {
     /**
       * Prefer low power when on battery, high performance when on mains.
       */
    DEFAULT,
     /**
       * Adapter that uses the least possible power. This is often an integerated GPU.
       */
    LOW_POWER,
     /**
       * Adapter that has the highest performance. This is often a discrete GPU.
       */
    HIGH_PERFORMANCE,
}