package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuStencilOperation {
    /** Keep stencil value unchanged. */
    KEEP,
    /** Set stencil value to zero. */
    ZERO,
    /**
     * Replace stencil value with value provided in most recent call to
     * [`RenderPass::set_stencil_reference`].
     */
    REPLACE,
    /** Bitwise inverts stencil value. */
    INVERT,
    /** Increments stencil value by one, clamping on overflow. */
    INCREMENT_CLAMP,
    /** Decrements stencil value by one, clamping on underflow. */
    DECREMENT_CLAMP,
    /** Increments stencil value by one, wrapping on overflow. */
    INCREMENT_WRAP,
    /** Decrements stencil value by one, wrapping on underflow. */
    DECREMENT_WRAP,
}
