package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuTextureAspect {
     /**
       * Depth, Stencil, and Color.
       */
    ALL,
     /**
       * Stencil.
       */
    STENCIL_ONLY,
     /**
       * Depth.
       */
    DEPTH_ONLY,
}