package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuVertexFormat {
     /**
       * Two unsigned bytes (u8). `uvec2` in shaders.
       */
    UCHAR2,
     /**
       * Four unsigned bytes (u8). `uvec4` in shaders.
       */
    UCHAR4,
     /**
       * Two signed bytes (i8). `ivec2` in shaders.
       */
    CHAR2,
     /**
       * Four signed bytes (i8). `ivec4` in shaders.
       */
    CHAR4,
     /**
       * Two unsigned bytes (u8). [0, 255] converted to float [0, 1] `vec2` in shaders.
       */
    UCHAR2_NORM,
     /**
       * Four unsigned bytes (u8). [0, 255] converted to float [0, 1] `vec4` in shaders.
       */
    UCHAR4_NORM,
     /**
       * Two signed bytes (i8). [-127, 127] converted to float [-1, 1] `vec2` in shaders.
       */
    CHAR2_NORM,
     /**
       * Four signed bytes (i8). [-127, 127] converted to float [-1, 1] `vec4` in shaders.
       */
    CHAR4_NORM,
     /**
       * Two unsigned shorts (u16). `uvec2` in shaders.
       */
    USHORT2,
     /**
       * Four unsigned shorts (u16). `uvec4` in shaders.
       */
    USHORT4,
     /**
       * Two unsigned shorts (i16). `ivec2` in shaders.
       */
    SHORT2,
     /**
       * Four unsigned shorts (i16). `ivec4` in shaders.
       */
    SHORT4,
     /**
       * Two unsigned shorts (u16). [0, 65535] converted to float [0, 1] `vec2` in shaders.
       */
    USHORT2_NORM,
     /**
       * Four unsigned shorts (u16). [0, 65535] converted to float [0, 1] `vec4` in shaders.
       */
    USHORT4_NORM,
     /**
       * Two signed shorts (i16). [-32767, 32767] converted to float [-1, 1] `vec2` in shaders.
       */
    SHORT2_NORM,
     /**
       * Four signed shorts (i16). [-32767, 32767] converted to float [-1, 1] `vec4` in shaders.
       */
    SHORT4_NORM,
     /**
       * Two half-precision floats (no Rust equiv). `vec2` in shaders.
       */
    HALF2,
     /**
       * Four half-precision floats (no Rust equiv). `vec4` in shaders.
       */
    HALF4,
     /**
       * One single-precision float (f32). `float` in shaders.
       */
    FLOAT,
     /**
       * Two single-precision floats (f32). `vec2` in shaders.
       */
    FLOAT2,
     /**
       * Three single-precision floats (f32). `vec3` in shaders.
       */
    FLOAT3,
     /**
       * Four single-precision floats (f32). `vec4` in shaders.
       */
    FLOAT4,
     /**
       * One unsigned int (u32). `uint` in shaders.
       */
    UINT,
     /**
       * Two unsigned ints (u32). `uvec2` in shaders.
       */
    UINT2,
     /**
       * Three unsigned ints (u32). `uvec3` in shaders.
       */
    UINT3,
     /**
       * Four unsigned ints (u32). `uvec4` in shaders.
       */
    UINT4,
     /**
       * One signed int (i32). `int` in shaders.
       */
    INT,
     /**
       * Two signed ints (i32). `ivec2` in shaders.
       */
    INT2,
     /**
       * Three signed ints (i32). `ivec3` in shaders.
       */
    INT3,
     /**
       * Four signed ints (i32). `ivec4` in shaders.
       */
    INT4,
}