package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuLoadOp {
     /**
       * Clear the output attachment with the clear color. Clearing is faster than loading.
       */
    CLEAR,
     /**
       * Do not clear output attachment.
       */
    LOAD,
}