package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public final class Wgpu{

    /**
     * Buffer-Texture copies must have [`bytes_per_row`] aligned to this number.
     *
     * This doesn't apply to [`Queue::write_texture`].
     *
     * [`bytes_per_row`]: TextureDataLayout::bytes_per_row
     */
    public static final int COPY_BYTES_PER_ROW_ALIGNMENT = 256;
    public static final int DESIRED_NUM_FRAMES = 3;
    public static final int MAX_ANISOTROPY = 16;
    public static final int MAX_COLOR_TARGETS = 4;
    public static final int MAX_MIP_LEVELS = 16;
    public static final int MAX_VERTEX_BUFFERS = 16;

}