package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuTextureViewDimension {
    /** A one dimensional texture. `texture1D` in glsl shaders. */
    D1,
    /** A two dimensional texture. `texture2D` in glsl shaders. */
    D2,
    /** A two dimensional array texture. `texture2DArray` in glsl shaders. */
    D2_ARRAY,
    /** A cubemap texture. `textureCube` in glsl shaders. */
    CUBE,
    /** A cubemap array texture. `textureCubeArray` in glsl shaders. */
    CUBE_ARRAY,
    /** A three dimensional texture. `texture3D` in glsl shaders. */
    D3,
}
