package io.github.kgpu.wgpuj.jni;


/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuTextureComponentType {
     /**
       * They see it as a floating point number `texture1D`, `texture2D` etc
       */
    FLOAT,
     /**
       * They see it as a signed integer `itexture1D`, `itexture2D` etc
       */
    SINT,
     /**
       * They see it as a unsigned integer `utexture1D`, `utexture2D` etc
       */
    UINT,
}