package io.github.kgpu.wgpuj.jni;

/** NOTE: THIS FILE WAS PRE-GENERATED BY JNR_GEN! */
public enum WgpuStoreOp {
    /**
     * Clear the render target. If you don't care about the contents of the target, this can be
     * faster.
     */
    CLEAR,
    /** Store the result of the renderpass. */
    STORE,
}
